# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/VIVADO/src/constraint.xdc

# IP: ip/Driver_HDMI_0_3/Driver_HDMI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Driver_HDMI_0 || ORIG_REF_NAME==Driver_HDMI_0} -quiet] -quiet
